Repository elementary/switchboard-plug-bluetooth, pull requests merged in 2021-03, with the labels that each got.

#163 Manager: Remove unnceccesary begin
  src/Services/Manager.vala
Labels: Bitesize

#162 Fix compiler warnings
  src/DeviceRow.vala
Labels: Bitesize

#169 Make switchboard the default agent
  src/Services/Manager.vala
Labels: Priority: Critical

#167 Release 2.3.5
  data/io.elementary.switchboard.bluetooth.appdata.xml.in
  meson.build
Labels: Release
